### ISSUE TITLE
使用MiniHUD的显示光照功能替代Lighty模组

### ISSUE THREAD

**Issue by Aunst** [OrzMiku/lunarfox#1]
**Is your request related to a problem? Please describe if so.**

MiniHUD可以显示方块亮度，数字也会跟随玩家旋转

**Describe the mod you'd like to add, remove, or change**

移除Lighty模组

**List alternative mods or solutions you've considered**

给MiniHUD显示光照等级功能一个热键：（config/minihud.json）
```json
{
  "RendererHotkeys": {
    "overlayLightLevel": {
      "keys": "F7"
    }
  }
}
```

**Additional context**

![2024-11-15_17 55 25](https://github.com/user-attachments/assets/1bbe728a-cc7e-4e06-b209-998a3452157e)
MiniHUD显示的光照等级

**Comment by OrzMiku** [comment]
善，已更新

**Comment by OrzMiku** [comment]
可能会添加回Lighty模组，数字显示光照等级在一些光影下无法正常显示，Lighty支持另一种显示方式。重新打开此Issue。
