### ISSUE TITLE
Tweakeroo有灵魂出鞘

### ISSUE THREAD

**Issue by Aunst** [OrzMiku/lunarfox#8]
整合包默认没给Tweakeroo的灵魂出窍功能快捷键。选用Freecam是因为兼容性更好吗？（之前好像看过说Tweakeroo的灵魂出鞘在一些情况下能看见手？我自己用没发现问题）

我给Tweakeroo灵魂出窍分配的快捷键的配置文件部分：
```json
{
  "GenericHotkeys": {
    "freeCameraPlayerMovement": {
      "keys": "MINUS"
    }
  }
  "TweakHotkeys": {
    "tweakFreeCamera": {
      "keys": "EQUAL"
    }
  }
}
```

![图片](https://github.com/user-attachments/assets/22b84052-9cc5-4906-bdbe-4a8537865295)
设置界面

**Comment by OrzMiku** [comment]
选用Freecam是因为Freecam不能穿墙。
